In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
np.set_printoptions(precision=2)

dataset = np.array([
    [2104, 5, 1, 45, 460],
    [1416, 3, 2, 40, 232],
    [1534, 3, 2, 30, 315],
    [1600, 4, 2, 30, 389],
    [852, 2, 1, 36, 178],
])

raw_inputs = dataset[:, :-1]
outputs = dataset[:, -1]
scaler = StandardScaler()
inputs = scaler.fit_transform(raw_inputs)
print("Scaled inputs:")
print(inputs)

sgdr = SGDRegressor(max_iter=100000)
sgdr.fit(inputs, outputs)
print(sgdr)
print(f"number of iterations completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")
print(sgdr.intercept_)
print(sgdr.coef_)


Scaled inputs:
[[ 1.5   1.57 -1.22  1.51]
 [-0.21 -0.39  0.82  0.65]
 [ 0.08 -0.39  0.82 -1.07]
 [ 0.25  0.59  0.82 -1.07]
 [-1.62 -1.37 -1.22 -0.03]]
SGDRegressor(max_iter=100000)
number of iterations completed: 1815, number of weight updates: 9076.0
[314.8]
[ 49.25  64.61 -24.29 -39.63]
