In [1]:
import numpy as np


def sig(x):
    return 1 / (1 + np.exp(-x))


training_data = np.array([
    [0, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1],
    [1, 1, 1, 1]])

training_inputs = training_data[:, 0:3]

training_outputs = training_data[:, 3:]

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1

print(synaptic_weights)


[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


Just check each step one by one

In [2]:
outputs = sig(np.dot(training_inputs, synaptic_weights))
err = training_outputs - outputs
adjustments = np.dot(training_inputs.T, err * outputs * (1 - outputs))
print("Synaptic weights before training: ")
print(synaptic_weights)
print("Errors:")
print(err)
print("Adjustment:")
print(adjustments)
synaptic_weights += adjustments
print("Synaptic weights after training: ")
print(synaptic_weights)

Synaptic weights before training: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Errors:
[[-0.5       ]
 [-0.2689864 ]
 [-0.60841366]
 [-0.36375058]
 [ 0.54139404]
 [ 0.76237183]
 [ 0.43175534]
 [ 0.6737243 ]]
Adjustment:
[[0.5265589 ]
 [0.02488857]
 [0.14913351]]
Synaptic weights after training: 
[[ 0.36060291]
 [ 0.46553755]
 [-0.85063774]]
