In [1]:
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt
from copy import deepcopy


def sig(x):
    return 1 / (1 + np.exp(-x))


def shp(x):
    return x.reshape(len(x), -1)

def polynom(inputs: np.ndarray, degree=2):
    if degree < 2:
        raise Exception("Degree should be at least 2")

    transposed = inputs.T
    base = len(transposed)

    pols = []
    newgen = []
    for i in range(base):
        newgen.append([i])
    pols.extend(newgen)

    for deg in range(1, degree):
        lastgen = newgen
        newgen = []
        for p in lastgen:
            for i in range(p[-1], base):
                pnext = [*p, i]
                pnext.sort()
                newgen.append(pnext)
        pols.extend(newgen)

    new_inputs = []
    for p in pols:
        new_inputs.append(deepcopy(transposed[p[0]]))
        for i in p[1:]:
            new_inputs[-1] *= transposed[i]
    return np.array(new_inputs).T


dataset = np.array([
    [2104, 5, 1, 45, 460],
    [1416, 3, 2, 40, 232],
    [1534, 3, 2, 30, 315],
    [1600, 4, 2, 30, 389],
    [852, 2, 1, 36, 178],
    [2104, 5, 1, 45, 460],
    [1416, 3, 2, 40, 232],
    [1534, 3, 2, 30, 315],
    [1600, 4, 2, 30, 389],
    [852, 2, 1, 36, 178],
])
x_train = dataset[:, :-1]
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x_train)
x_train = np.array(norm_l(x_train))
y_train = dataset[:, -1:]

tf.random.set_seed(1234)
l1 = tf.keras.layers.Dense(units=5, activation='sigmoid')
print(l1(x_train))
weights, biases = l1.weights
l1.set_weights([np.zeros((4,5)), np.zeros(5)])
print(weights)
print(biases)
print(l1(x_train))


tf.Tensor(
[[0.28533226 0.4422932  0.8316489  0.30507684 0.6832273 ]
 [0.6859867  0.59014505 0.37921956 0.6743647  0.36048767]
 [0.5295911  0.5523414  0.31133834 0.33975872 0.43897912]
 [0.4864415  0.6773351  0.3636869  0.18710798 0.33614668]
 [0.51811326 0.2526757  0.5618739  0.9027821  0.6748987 ]
 [0.28533226 0.4422932  0.8316489  0.30507684 0.6832273 ]
 [0.6859867  0.59014505 0.37921956 0.6743647  0.36048767]
 [0.5295911  0.5523414  0.31133834 0.33975872 0.43897912]
 [0.4864415  0.6773351  0.3636869  0.18710798 0.33614668]
 [0.51811326 0.2526757  0.5618739  0.9027821  0.6748987 ]], shape=(10, 5), dtype=float32)
<tf.Variable 'dense/kernel:0' shape=(4, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>
<tf.Variable 'dense/bias:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>
tf.Tensor(
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 