In [1]:
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt
from copy import deepcopy


def sig(x):
    return 1 / (1 + np.exp(-x))


def shp(x):
    return x.reshape(len(x), -1)

def polynom(inputs: np.ndarray, degree=2):
    if degree < 2:
        raise Exception("Degree should be at least 2")

    transposed = inputs.T
    base = len(transposed)

    pols = []
    newgen = []
    for i in range(base):
        newgen.append([i])
    pols.extend(newgen)

    for deg in range(1, degree):
        lastgen = newgen
        newgen = []
        for p in lastgen:
            for i in range(p[-1], base):
                pnext = [*p, i]
                pnext.sort()
                newgen.append(pnext)
        pols.extend(newgen)

    new_inputs = []
    for p in pols:
        new_inputs.append(deepcopy(transposed[p[0]]))
        for i in p[1:]:
            new_inputs[-1] *= transposed[i]
    return np.array(new_inputs).T


dataset = np.array([
    [2104, 5, 1, 45, 460],
    [1416, 3, 2, 40, 232],
    [1534, 3, 2, 30, 315],
    [1600, 4, 2, 30, 389],
    [852, 2, 1, 36, 178],
    [2104, 5, 1, 45, 460],
    [1416, 3, 2, 40, 232],
    [1534, 3, 2, 30, 315],
    [1600, 4, 2, 30, 389],
    [852, 2, 1, 36, 178],
])
x_train = dataset[:, :-1]
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x_train)
x_train = np.array(norm_l(x_train))
y_train = dataset[:, -1:]

tf.random.set_seed(1234)
l1 = tf.keras.layers.Dense(units=5, activation='sigmoid')
print("INITIAL OUTPUTS:")
print(l1(x_train).numpy())
weights, biases = l1.weights
print("WEIGHTS:")
print(weights.numpy())
print("BIASES:")
print(biases.numpy())
l1.set_weights([np.zeros((4,5)), np.zeros(5)])
print("OUTPUTS AFTER SETTING WEIGHTS AND BIASES TO ZERO:")
print(l1(x_train).numpy())


INITIAL OUTPUTS:
[[0.34485415 0.49671987 0.27991873 0.35904345 0.8617157 ]
 [0.5452108  0.39545584 0.66618335 0.55509824 0.48121813]
 [0.7068497  0.4879042  0.41902053 0.605126   0.33525658]
 [0.62904274 0.37522605 0.33342364 0.7157603  0.41612902]
 [0.2793181  0.7302342  0.7813289  0.2704835  0.32491803]
 [0.34485415 0.49671987 0.27991873 0.35904345 0.8617157 ]
 [0.5452108  0.39545584 0.66618335 0.55509824 0.48121813]
 [0.7068497  0.4879042  0.41902053 0.605126   0.33525658]
 [0.62904274 0.37522605 0.33342364 0.7157603  0.41612902]
 [0.2793181  0.7302342  0.7813289  0.2704835  0.32491803]]
WEIGHTS:
[[ 0.68771636  0.24658394 -0.7033846  -0.3081981   0.33676505]
 [-0.47450083 -0.51202404 -0.25505143  0.5582584   0.29610538]
 [ 0.4042021  -0.5603659   0.16330695  0.59686446 -0.19186008]
 [-0.2883597  -0.17630494  0.47101378 -0.17217839  0.41166604]]
BIASES:
[0. 0. 0. 0. 0.]
OUTPUTS AFTER SETTING WEIGHTS AND BIASES TO ZERO:
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0