In [1]:
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt
from copy import deepcopy


def sig(x):
    return 1 / (1 + np.exp(-x))

def dense(a_in, w, b, g=sig):
    return g(np.matmul(a_in,w) + b)


# totensor = tf.convert_to_tensor
IN = np.array([
    [1, 2], 
    [2, 4]
])
# IN = totensor(IN, dtype='float64')
W1 = np.array([
    [1, 0, 1],
    [0, 1, 0]
])
# W1 = totensor(W1)
B1 = np.array([0, 10, 20])
# B1 = totensor(B1)
W2 = np.array([
    [1],
    [1],
    [0]
])
# W2 = totensor(W2)
B2 = np.array([1])
# B2 = totensor(B2)
a1 = dense(IN, W1, B1)
a2 = dense(a1, W2, B2)

L1 = tf.keras.layers.Dense(units=3, activation='sigmoid')
L1.build(input_shape=(2, 2))
L1.set_weights([W1, B1])
A1 = np.array(L1(IN))
L2 = tf.keras.layers.Dense(units=1, activation='sigmoid')
L2.build(input_shape=(2, 3))
L2.set_weights([W2, B2])
A2 = np.array(L2(A1))

print("WEIGHTS, BIASES:")
print("L1 (2 in, 3 out):")
print(W1)
print(B1)
print("L2 (3 in, 1 out):")
print(W2)
print(B2)
print("HANDMADE LAYERS OUTPUTS:")
print("L1:")
print(a1)
print("L2:")
print(a2)
print("KERAS LAYERS OUTPUTS:")
print("L1:")
print(A1)
print("L2:")
print(A2)
print("DIFFERENCE: 0")

WEIGHTS, BIASES:
L1 (2 in, 3 out):
[[1 0 1]
 [0 1 0]]
[ 0 10 20]
L2 (3 in, 1 out):
[[1]
 [1]
 [0]]
[1]
HANDMADE LAYERS OUTPUTS:
L1:
[[0.73105858 0.99999386 1.        ]
 [0.88079708 0.99999917 1.        ]]
L2:
[[0.9388343 ]
 [0.94688892]]
KERAS LAYERS OUTPUTS:
L1:
[[0.7310586  0.99999386 1.        ]
 [0.8807971  0.99999917 1.        ]]
L2:
[[0.9388343]
 [0.9468889]]
DIFFERENCE: 0
